import type { Metadata } from 'next';
import Header from '@/components/layout/HeaderNav';
import Footer from '@/components/layout/Footer';
import TopBar from '@/components/layout/TopBar';

import './globals.css';

export const metadata: Metadata = {
	title: 'Olympia Garden Materials',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='main'>
				<TopBar />
				<Header />
				<main className='main'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
