import type { Metadata } from 'next';
import Header from '@/components/layout/HeaderNav';
import Footer from '@/components/layout/Footer';
import TopBar from '@/components/layout/TopBar';
import BreadCrumb from '@/components/breadcrumbs';
import Providers from './providers';
import classes from './layout.module.css';

import './globals.css';

export const metadata: Metadata = {
	title: 'Olympia Garden Materials',
	description: 'Generated by create next app',
};

const containerClasses = `${classes.bread_crumb} ${classes.flex} ${classes.py_5}`;

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			{/* <script
				async
				src='https://cdn.tiny.cloud/1/rwkayo3b59qnedantqw0om73dqwpiuqicaxgz08kgqxkvgfn/tinymce/6/tinymce.min.js'
				referrerPolicy='origin'
			/> */}
			<body>
				<Providers>
					<TopBar />
					<Header />
					<BreadCrumb
						homeElement={'Home'}
						separator={<span> &gt; </span>}
						activeClasses={classes.text_slate_500}
						containerClasses={containerClasses}
						listClasses={`${classes.mx_2} font-bold`}
						capitalizeLinks
					/>
					<main className='main'>{children}</main>
					<Footer />
				</Providers>
				<div id='backdrop-hook'></div>
				<div id='modal-hook'></div>
			</body>
		</html>
	);
}
